version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: 'kata-mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=kata
      - MYSQL_DATABASE=kata
      - MYSQL_USER=kata
      - MYSQL_PASSWORD=kata
    volumes:
      - katamysqldata:/var/lib/mysql
    ports:
      - "3333:3306"
volumes:
  katamysqldata: